In [1]:
import tensorflow as tf
import numpy as np

In [2]:
ten=tf.constant([3,4,5,6,6])

In [3]:
tf.shape(ten)

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([5], dtype=int32)>

In [4]:
tf.argmax(ten)

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [5]:
ten.shape

TensorShape([5])

In [6]:
np_array=np.array([10,12,23,32,42])

In [7]:
new_tensor=tf.constant(np_array)

In [8]:
new_tensor

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([10, 12, 23, 32, 42])>

In [9]:
new_tensor.dtype

tf.int64

In [13]:
tf.range(0,10,2,dtype=tf.float32)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 2., 4., 6., 8.], dtype=float32)>

In [18]:
x = tf.constant([16, 12, 10],dtype=tf.int32)
y = tf.constant([4, 6, 2],dtype=tf.int32)
result=tf.divide(x,y)
print(result)

tf.Tensor([4. 2. 5.], shape=(3,), dtype=float64)


In [19]:
print(x+y)

tf.Tensor([20 18 12], shape=(3,), dtype=int32)


In [20]:
two_d_tensor=tf.constant([[16, 12, 10],[4,6,2]])

In [23]:
two_d_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  2], dtype=int32)>

Normal And Uniform Distiribution

In [25]:
normal_dist=tf.random.normal(shape=[10,],mean=5,stddev=1)
print(normal_dist)

tf.Tensor(
[3.8045127 1.9942639 3.9256225 5.473755  5.794848  5.0839877 2.8672507
 6.0396595 5.016508  4.610773 ], shape=(10,), dtype=float32)


In [30]:
uniform_dist=tf.random.uniform(shape=[10,],minval=0,maxval=10)
print(uniform_dist)

tf.Tensor(
[1.382283   0.53791046 5.478163   1.6142869  9.747314   0.32578826
 5.367048   7.251478   0.5634737  4.6611667 ], shape=(10,), dtype=float32)
